services:
  mariadb:  # Servicio para MariaDB
    image: mariadb:11  # Imagen oficial de MariaDB, puedes ajustar la versi칩n si lo necesitas
    restart: unless-stopped  # Reinicia autom치ticamente el contenedor si se detiene
    environment:
      # Variables de entorno usadas por MariaDB para inicializar la base de datos
      MARIADB_ROOT_PASSWORD: password  # Contrase침a para el usuario root
      MARIADB_DATABASE: atenea  # Nombre de la base de datos a crear al inicio
      MARIADB_USER: atenea  # Usuario a crear
      MARIADB_PASSWORD: password  # Contrase침a del usuario creado
    ports:
      - "3306:3306"  # Expone el puerto de MariaDB al host local (opcional si solo se comunica con la app)
    volumes:
      - ./mariadb:/var/lib/mysql
